# Generated by Django 5.0.7 on 2025-07-23 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipoControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(blank=True, max_length=100, null=True)),
                ('capacidad', models.IntegerField(blank=True, null=True)),
                ('codigo', models.CharField(blank=True, max_length=100, null=True)),
                ('fechaCalibracion', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='trazabilidad',
            old_name='cantidadCamiones',
            new_name='cantidadTransporte',
        ),
        migrations.AddField(
            model_name='lotedespacho',
            name='DUS',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='lotedespacho',
            name='DUSAvanceComposito',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lotedespacho',
            name='DUSFinales',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lotedespacho',
            name='DV',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='lotedespacho',
            name='LALFinales',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lotedespacho',
            name='aduana',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='lotedespacho',
            name='calidad',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='lotedespacho',
            name='cliente',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='lotedespacho',
            name='contratoAnglo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='lotedespacho',
            name='contratoCochilco',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='lotedespacho',
            name='exportador',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='lotedespacho',
            name='fechaDUS',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lotedespacho',
            name='fechaEntregaLab',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lotedespacho',
            name='fechaEntregaLabAduana',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lotedespacho',
            name='fechaEnvioReporte',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lotedespacho',
            name='fechaTermino',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lotedespacho',
            name='listaVerificacion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='lotedespacho',
            name='lugarDescarga',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='lotedespacho',
            name='numResolucionSNA',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='lotedespacho',
            name='paisDescarga',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='lotedespacho',
            name='refFocus',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='lotedespacho',
            name='registroINN',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='lotedespacho',
            name='resguardoTestigoAduana',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='lotedespacho',
            name='rutExportador',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='trazabilidad',
            name='fechaPreparacionMuestra',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trazabilidad',
            name='horaPreparacionMuestra',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trazabilidadmecanica',
            name='fechaSobre',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trazabilidadmecanica',
            name='nSubLote',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bodega',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='despachocamion',
            name='CuFino',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='despachocamion',
            name='brutoDestino',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='despachocamion',
            name='diferenciaHumeda',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='despachocamion',
            name='diferenciaSeca',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='despachocamion',
            name='netoHumedoDestino',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='despachocamion',
            name='netoHumedoOrigen',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='despachocamion',
            name='taraDestino',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='despachoembarque',
            name='CuFino',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='despachoembarque',
            name='odometroFinal',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='despachoembarque',
            name='odometroInicial',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='despachoembarque',
            name='pesoLote',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='despachoembarque',
            name='porcHumedad',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='detallebodega',
            name='despacho',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='detallebodega',
            name='ingreso',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='emails',
            name='emailDestino',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='emails',
            name='emailOrigen',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='humedades',
            name='nLata1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='humedades',
            name='nLata2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='lote',
            name='porcHumedad',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='loteinventario',
            name='porcHumedad',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='loterecepcion',
            name='CuDestino',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='loterecepcion',
            name='CuOrigen',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='loterecepcion',
            name='diferenciaPeso',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='loterecepcion',
            name='pesoBrutoHumedo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='loterecepcion',
            name='pesoNetoHumedo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='loterecepcion',
            name='pesoNetoSeco',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='loterecepcion',
            name='pesoTara',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='loterecepcion',
            name='porcHumedad',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='recepciontransporte',
            name='CuFino',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='recepciontransporte',
            name='brutoDestino',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='recepciontransporte',
            name='brutoOrigen',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='recepciontransporte',
            name='diferenciaHumeda',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='recepciontransporte',
            name='diferenciaSeca',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='recepciontransporte',
            name='netoHumedoDestino',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='recepciontransporte',
            name='netoHumedoOrigen',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='recepciontransporte',
            name='taraDestino',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='recepciontransporte',
            name='taraOrigen',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='trazabilidadmecanica',
            name='DUS',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trazabilidadmecanica',
            name='bodega',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trazabilidadmecanica',
            name='cliente',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trazabilidadmecanica',
            name='cochilco',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trazabilidadmecanica',
            name='contrato',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trazabilidadmecanica',
            name='exportador',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trazabilidadmecanica',
            name='material',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trazabilidadmecanica',
            name='muestreadoPor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trazabilidadmecanica',
            name='nave',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trazabilidadmecanica',
            name='pesoNetoHumedo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='trazabilidadmecanica',
            name='pesoNetoSeco',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='trazabilidadmecanica',
            name='porcHumedad',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='trazabilidadmecanica',
            name='puertoDestino',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trazabilidadmecanica',
            name='responsable',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
