# Generated by Django 5.1.1 on 2024-10-09 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nServ', models.IntegerField()),
                ('fServ', models.DateField()),
                ('lServ', models.CharField(max_length=100)),
                ('eServ', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nSoli', models.IntegerField()),
                ('fiSoli', models.DateField()),
                ('ftSoli', models.DateField()),
                ('lSoli', models.CharField(max_length=100)),
                ('eSoli', models.CharField(max_length=20)),
            ],
        ),
    ]
