# Generated by Django 5.1.1 on 2024-10-14 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_servicio_nserv_alter_solicitud_nsoli_lote_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Despacho',
            fields=[
                ('nDespacho', models.IntegerField(primary_key=True, serialize=False)),
                ('fCreacionDespacho', models.DateField()),
                ('porcHumedad', models.DecimalField(decimal_places=3, max_digits=6)),
                ('cantCamiones', models.IntegerField()),
                ('taraCamiones', models.IntegerField()),
                ('pesoBruto', models.IntegerField()),
                ('pesoNeto', models.IntegerField()),
                ('pesoNetoSeco', models.IntegerField()),
                ('observacion', models.CharField(max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='recepcion',
            name='nServicio',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.servicio'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recepcion',
            name='nLote',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='DespachoCamion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fDespacho', models.DateField()),
                ('hDespacho', models.TimeField()),
                ('nServicio', models.IntegerField()),
                ('nCamion', models.IntegerField()),
                ('patenteCamion', models.IntegerField()),
                ('guiaDespacho', models.IntegerField()),
                ('taraCamion', models.IntegerField()),
                ('pesoBrutoCamion', models.IntegerField()),
                ('pesoNeto', models.IntegerField()),
                ('nDespacho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.despacho')),
                ('nLote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.lote')),
            ],
        ),
        migrations.CreateModel(
            name='RecepcionTransporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nRecepcion', models.IntegerField()),
                ('cantTransporte', models.IntegerField()),
                ('fOrigen', models.DateField()),
                ('hOrigen', models.TimeField()),
                ('idTransporteOrigen', models.IntegerField()),
                ('idCarro', models.IntegerField()),
                ('sellosOrigen', models.IntegerField()),
                ('netoHumedoOrigen', models.IntegerField()),
                ('idTransporteDestino', models.IntegerField()),
                ('idCarroDestino', models.IntegerField()),
                ('sellosDestino', models.IntegerField()),
                ('brutoDestino', models.IntegerField()),
                ('taraDestino', models.IntegerField()),
                ('netoHumedoDestino', models.IntegerField()),
                ('diferenciaHumeda', models.IntegerField()),
                ('diferenciaSeca', models.IntegerField()),
                ('nLote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.lote')),
            ],
        ),
    ]
