# Generated by Django 5.1.1 on 2024-10-16 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_solicitud_nserv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='nServ',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='nSoli',
            field=models.CharField(max_length=20),
        ),
    ]
