# Generated by Django 5.1.1 on 2024-10-16 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_servicio_nserv_alter_solicitud_nsoli'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='ftSoli',
            field=models.DateField(blank=True, null=True),
        ),
    ]
