# Generated by Django 5.1.1 on 2024-10-21 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_solicitud_ftsoli'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='cantBigbag',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='lote',
            name='cantCamiones',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='lote',
            name='cantVagones',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='lote',
            name='diferenciaPeso',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='lote',
            name='nLote',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='lote',
            name='pesoBrutoHumedo',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='lote',
            name='pesoNetoHumedo',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='lote',
            name='pesoNetoSeco',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='lote',
            name='pesoTara',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='lote',
            name='porcHumedad',
            field=models.IntegerField(blank=True),
        ),
    ]
