# Generated by Django 5.1.1 on 2024-10-24 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_lote_cantbigbag_alter_lote_cantcamiones_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lote',
            old_name='obs',
            new_name='observacion',
        ),
    ]
