# Generated by Django 5.1.1 on 2024-10-24 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_obs_lote_observacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoteDespacho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nLote', models.CharField(max_length=200, unique=True)),
                ('fLote', models.DateField()),
                ('observacion', models.CharField(max_length=200)),
                ('tipoTransporte', models.CharField(max_length=200)),
                ('cantCamiones', models.IntegerField(blank=True)),
                ('cantVagones', models.IntegerField(blank=True)),
                ('pesoBrutoHumedo', models.IntegerField(blank=True)),
                ('pesoTara', models.IntegerField(blank=True)),
                ('pesoNetoHumedo', models.IntegerField(blank=True)),
                ('porcHumedad', models.IntegerField(blank=True)),
                ('pesoNetoSeco', models.IntegerField(blank=True)),
                ('diferenciaPeso', models.IntegerField(blank=True)),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.servicio')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.solicitud')),
            ],
        ),
        migrations.CreateModel(
            name='LoteInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nLote', models.CharField(max_length=200, unique=True)),
                ('fLote', models.DateField()),
                ('observacion', models.CharField(max_length=200)),
                ('pesoNetoHumedo', models.IntegerField(blank=True)),
                ('porcHumedad', models.IntegerField(blank=True)),
                ('pesoNetoSeco', models.IntegerField(blank=True)),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.servicio')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.solicitud')),
            ],
        ),
        migrations.CreateModel(
            name='LoteRecepcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nLote', models.CharField(max_length=200, unique=True)),
                ('fLote', models.DateField()),
                ('observacion', models.CharField(max_length=200)),
                ('tipoTransporte', models.CharField(max_length=200)),
                ('cantCamiones', models.IntegerField(blank=True)),
                ('cantVagones', models.IntegerField(blank=True)),
                ('cantBigbag', models.IntegerField(blank=True)),
                ('pesoBrutoHumedo', models.IntegerField(blank=True)),
                ('pesoTara', models.IntegerField(blank=True)),
                ('pesoNetoHumedo', models.IntegerField(blank=True)),
                ('porcHumedad', models.IntegerField(blank=True)),
                ('pesoNetoSeco', models.IntegerField(blank=True)),
                ('diferenciaPeso', models.IntegerField(blank=True)),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.servicio')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.solicitud')),
            ],
        ),
    ]
