# Generated by Django 5.1.1 on 2024-10-24 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_lotedespacho_loteinventario_loterecepcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recepcion',
            name='nLote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.loterecepcion'),
        ),
    ]
