# Generated by Django 5.1.1 on 2024-10-30 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_loterecepcion_observacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loterecepcion',
            name='cantBigbag',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loterecepcion',
            name='cantCamiones',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loterecepcion',
            name='cantVagones',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loterecepcion',
            name='diferenciaPeso',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loterecepcion',
            name='observacion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='loterecepcion',
            name='pesoBrutoHumedo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loterecepcion',
            name='pesoNetoHumedo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loterecepcion',
            name='pesoNetoSeco',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loterecepcion',
            name='pesoTara',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loterecepcion',
            name='porcHumedad',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
