# Generated by Django 5.1.1 on 2024-11-11 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_recepciontransporte_nrecepcion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recepciontransporte',
            name='nServicio',
        ),
    ]
