# Generated by Django 5.1.1 on 2024-11-11 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_recepciontransporte_nservicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recepciontransporte',
            name='nLote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.loterecepcion'),
        ),
    ]
