# Generated by Django 5.1.1 on 2024-11-11 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_recepciontransporte_nlote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recepciontransporte',
            name='nLote',
            field=models.CharField(max_length=200),
        ),
    ]
