# Generated by Django 5.1.1 on 2024-11-13 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_recepciontransporte_nlote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='porcHumedad',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='lotedespacho',
            name='porcHumedad',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='loteinventario',
            name='porcHumedad',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='loterecepcion',
            name='porcHumedad',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
    ]
