# Generated by Django 5.1.1 on 2024-11-15 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_recepciontransporte_idcarro_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recepciontransporte',
            name='cantTransporte',
        ),
        migrations.AddField(
            model_name='recepciontransporte',
            name='bodegaDescarga',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='recepciontransporte',
            name='fDestino',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recepciontransporte',
            name='hDestino',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recepciontransporte',
            name='idTransporteOrigen',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
