# Generated by Django 5.1.1 on 2024-11-15 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_remove_recepciontransporte_canttransporte_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recepciontransporte',
            name='estado',
            field=models.CharField(default='pendiente', max_length=20),
            preserve_default=False,
        ),
    ]
