# Generated by Django 5.1.1 on 2024-12-06 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_recepciontransporte_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='token',
        ),
        migrations.AlterField(
            model_name='lotedespacho',
            name='cantCamiones',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lotedespacho',
            name='cantVagones',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lotedespacho',
            name='diferenciaPeso',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='lotedespacho',
            name='observacion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='lotedespacho',
            name='pesoBrutoHumedo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='lotedespacho',
            name='pesoNetoHumedo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='lotedespacho',
            name='pesoNetoSeco',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='lotedespacho',
            name='pesoTara',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='lotedespacho',
            name='porcHumedad',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='loterecepcion',
            name='diferenciaPeso',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='loterecepcion',
            name='pesoBrutoHumedo',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='loterecepcion',
            name='pesoNetoHumedo',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='loterecepcion',
            name='pesoNetoSeco',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='loterecepcion',
            name='pesoTara',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='loterecepcion',
            name='porcHumedad',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20),
        ),
    ]
