# Generated by Django 5.1.1 on 2024-12-17 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_remove_user_token_alter_lotedespacho_cantcamiones_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bodega',
            fields=[
                ('idBodega', models.AutoField(primary_key=True, serialize=False)),
                ('nombreBodega', models.CharField(max_length=200)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=200)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleBodega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingreso', models.DecimalField(blank=True, decimal_places=2, max_digits=200)),
                ('despacho', models.DecimalField(blank=True, decimal_places=2, max_digits=200)),
                ('idBodega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.bodega')),
            ],
        ),
    ]
