# Generated by Django 5.1.1 on 2024-12-18 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_bodega_detallebodega'),
    ]

    operations = [
        migrations.AddField(
            model_name='recepciontransporte',
            name='bodega',
            field=models.ForeignKey( on_delete=django.db.models.deletion.CASCADE, to='api.bodega'),
            preserve_default=False,
        ),
    ]
