# Generated by Django 5.1.1 on 2024-12-18 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_recepciontransporte_bodega'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallebodega',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detallebodega',
            name='hora',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detallebodega',
            name='tipo',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
