# Generated by Django 5.1.1 on 2024-12-24 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_detallebodega_fecha_detallebodega_hora_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recepciontransporte',
            name='diferenciaHumeda',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recepciontransporte',
            name='diferenciaSeca',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recepciontransporte',
            name='netoHumedoDestino',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=200),
            preserve_default=False,
        ),
    ]
