# Generated by Django 5.1.1 on 2025-01-02 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_alter_recepciontransporte_diferenciahumeda_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despachocamion',
            name='fDespacho',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='despachocamion',
            name='guiaDespacho',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='despachocamion',
            name='hDespacho',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='despachocamion',
            name='nCamion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='despachocamion',
            name='nServicio',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='despachocamion',
            name='patenteCamion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='despachocamion',
            name='pesoBrutoCamion',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=200),
        ),
        migrations.AlterField(
            model_name='despachocamion',
            name='pesoNeto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=200),
        ),
        migrations.AlterField(
            model_name='despachocamion',
            name='taraCamion',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=200),
        ),
    ]
