# Generated by Django 5.1.1 on 2025-01-02 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_alter_despachocamion_fdespacho_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='despachocamion',
            name='nDespacho',
        ),
    ]
