# Generated by Django 5.1.1 on 2025-01-02 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_remove_despachocamion_ndespacho'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despachocamion',
            name='nLote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.lotedespacho'),
        ),
    ]
