# Generated by Django 5.1.1 on 2025-01-09 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_alter_despachocamion_nlote'),
    ]

    operations = [
        migrations.AddField(
            model_name='despacho',
            name='estado',
            field=models.CharField(default='pendiente', max_length=20),
            preserve_default=False,
        ),
    ]
