# Generated by Django 5.1.1 on 2025-01-10 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_despacho_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='despachocamion',
            name='estado',
            field=models.CharField(default='pendiente', max_length=20),
            preserve_default=False,
        ),
    ]
