# Generated by Django 5.1.1 on 2025-01-17 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_despachocamion_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recepciontransporte',
            name='brutoDestino',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recepciontransporte',
            name='netoHumedoOrigen',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recepciontransporte',
            name='taraDestino',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=200),
            preserve_default=False,
        ),
    ]
