# Generated by Django 5.1.1 on 2025-01-21 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_rename_ncamion_despachocamion_batea_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='despachocamion',
            name='bodega',
        ),
    ]
