# Generated by Django 5.1.1 on 2025-01-26 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_despachocamion_bodega'),
    ]

    operations = [
        migrations.CreateModel(
            name='DespachoEmbarque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nLote', models.CharField(max_length=200)),
                ('odometroInicial', models.DecimalField(decimal_places=3, max_digits=6)),
                ('odometroFinal', models.DecimalField(decimal_places=3, max_digits=6)),
                ('horaInicial', models.TimeField()),
                ('horaFinal', models.TimeField()),
                ('fechaInicial', models.DateField()),
                ('fechaFinal', models.DateField()),
                ('pesoLote', models.DecimalField(decimal_places=3, max_digits=6)),
                ('porcHumedad', models.DecimalField(decimal_places=3, max_digits=6)),
                ('estado', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='lotedespacho',
            name='bodegaNave',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='lotedespacho',
            name='nombreNave',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
