# Generated by Django 5.1.1 on 2025-01-27 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_lotedespacho_cantsublotes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despachoembarque',
            name='fechaFinal',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='despachoembarque',
            name='horaFinal',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
