# Generated by Django 5.0.7 on 2025-01-27 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_alter_despachoembarque_odometrofinal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recepciontransporte',
            name='brutoDestino',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='recepciontransporte',
            name='diferenciaHumeda',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='recepciontransporte',
            name='diferenciaSeca',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='recepciontransporte',
            name='idTransporteDestino',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='recepciontransporte',
            name='netoHumedoDestino',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='recepciontransporte',
            name='netoHumedoOrigen',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='recepciontransporte',
            name='sellosDestino',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='recepciontransporte',
            name='taraDestino',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
